/*
	Generated by ship.py on Sat May 23 15:13:55 2020.
*/
#include "shipyard.hpp"
#include "test_maps.cpp"
#include "test_vectors.cpp"
#include "test_numerics.cpp"

int main(int argc, char* argv[])
{
	const auto tests = sy::create_tests({
		TESTFUNC(test_valid_vectors),
		TESTFUNC(test_valid_numerics),
		TESTFUNC(test_invalid_vectors),
		TESTFUNC(test_invalid_numerics),
		TESTFUNC(test_valid_unordered_map),
		TESTFUNC(test_invalid_vectors_size),
		TESTFUNC(test_invalid_unordered_map_keys),
		TESTFUNC(test_invalid_unordered_map_values),
	});
	sy::run(tests, true);
	return 0;
}
